name: Weekly GitHub Actions Update

on:
  # Run every Monday at 10:00 AM UTC
  schedule:
    - cron: '0 10 * * 1'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      mode:
        description: 'Update mode'
        type: choice
        options:
          - 'update-to-latest'
          - 'convert-to-sha'
          - 'convert-main-to-release'
        default: 'update-to-latest'
      
      dry-run:
        description: 'Dry run (preview changes only)'
        type: boolean
        default: false

jobs:
  update-github-actions:
    name: Update GitHub Actions
    # Call the reusable workflow from this repository
    uses: ./.github/workflows/update-actions.yml
    with:
      files: '.github/workflows/*.yml'
      mode: ${{ inputs.mode || 'update-to-latest' }}
      dry-run: ${{ inputs.dry-run || false }}
      create-pr: true
      pr-title: '🤖 Weekly GitHub Actions Update'
      pr-body: |
        ## 🤖 Automated Weekly GitHub Actions Update
        
        This PR automatically updates GitHub Actions in workflow files to their latest releases.
        
        ### What's Updated
        - ✅ Updated actions to use SHA references with latest release tags
        - 🔒 Improved security through SHA pinning
        - 🚀 Access to latest features and bug fixes
        
        ### Review Checklist
        - [ ] Review the updated action versions
        - [ ] Check that workflows still function as expected
        - [ ] Verify no breaking changes in updated actions
        
        **Scheduled**: Every Monday at 10:00 AM UTC  
        **Generated by**: [github-actions-tag-2-sha](https://github.com/dgwhited/github-actions-tag-2-sha)
        
        Safe to merge! 🚢
      pr-labels: 'dependencies, automated-pr, github-actions, weekly-update'
      branch-name: 'weekly-actions-update'
      commit-message: '🤖 Weekly update of GitHub Actions to latest releases'
    # secrets:
      # Optional: Pass a custom token for advanced use cases
      # By default, uses the built-in GITHUB_TOKEN automatically
      # token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}